#pragma once

#define RXN_MOUSE_BUTTON_1         0
#define RXN_MOUSE_BUTTON_2         1
#define RXN_MOUSE_BUTTON_3         2
#define RXN_MOUSE_BUTTON_4         3
#define RXN_MOUSE_BUTTON_5         4
#define RXN_MOUSE_BUTTON_6         5
#define RXN_MOUSE_BUTTON_7         6
#define RXN_MOUSE_BUTTON_8         7
#define RXN_MOUSE_BUTTON_LAST      RXN_MOUSE_BUTTON_8
#define RXN_MOUSE_BUTTON_LEFT      RXN_MOUSE_BUTTON_1
#define RXN_MOUSE_BUTTON_RIGHT     RXN_MOUSE_BUTTON_2
#define RXN_MOUSE_BUTTON_MIDDLE    RXN_MOUSE_BUTTON_3